name: Feature Request
description: Suggest an idea or improvement.
title: "[Feature]: "
labels:
  - enhancement
  - needs-triage
body:
  - type: textarea
    attributes:
      label: Summary
      description: What would you like to see added or changed?
      placeholder: "It would be great if..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem / Motivation
      description: What problem does this solve? Who benefits?
      placeholder: "This helps because..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: How you think it should work.
      placeholder: "I imagine it working like..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternative approaches.
      placeholder: "I tried..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Links, screenshots, or examples.
    validations:
      required: false
